/*
  Tam 78 Kartlık Tarot Destesi
  Major Arcana (22 kart) + Minor Arcana (56 kart) = 78 kart
  Mobil uyumlu tarot uygulaması için hazırlanmıştır
*/

import { TarotCard } from './a-tarot-helpers'

// 78 kartlık tam tarot destesi
export const fullTarotDeck: TarotCard[] = [
  // Major Arcana (22 kart)
  { id: 0, name: "The Fool", nameTr: "Deli", suit: "major", number: 0, meaning: { upright: "New beginnings, innocence, spontaneity", reversed: "Recklessness, taken advantage of" }, meaningTr: { upright: "Yeni başlangıçlar, masumiyet, spontanlık", reversed: "Dikkatsizlik, istismar edilme" }, keywords: ["new beginnings", "innocence"], keywordsTr: ["yeni başlangıçlar", "masumiyet"] },
  { id: 1, name: "The Magician", nameTr: "Büyücü", suit: "major", number: 1, meaning: { upright: "Manifestation, resourcefulness, power", reversed: "Manipulation, poor planning" }, meaningTr: { upright: "Tezahür, beceriklilik, güç", reversed: "Manipülasyon, kötü planlama" }, keywords: ["manifestation", "power"], keywordsTr: ["tezahür", "güç"] },
  { id: 2, name: "The High Priestess", nameTr: "Yüksek Rahibe", suit: "major", number: 2, meaning: { upright: "Intuition, sacred knowledge, divine feminine", reversed: "Secrets, disconnected from intuition" }, meaningTr: { upright: "Sezgi, kutsal bilgi, ilahi dişilik", reversed: "Sırlar, sezgiden kopukluk" }, keywords: ["intuition", "mystery"], keywordsTr: ["sezgi", "gizem"] },
  { id: 3, name: "The Empress", nameTr: "İmparatoriçe", suit: "major", number: 3, meaning: { upright: "Femininity, beauty, nature, nurturing", reversed: "Creative block, dependence" }, meaningTr: { upright: "Kadınsılık, güzellik, doğa", reversed: "Yaratıcı blok, bağımlılık" }, keywords: ["femininity", "beauty"], keywordsTr: ["kadınsılık", "güzellik"] },
  { id: 4, name: "The Emperor", nameTr: "İmparator", suit: "major", number: 4, meaning: { upright: "Authority, establishment, structure", reversed: "Domination, excessive control" }, meaningTr: { upright: "Otorite, kurumsallık, yapı", reversed: "Tahakküm, aşırı kontrol" }, keywords: ["authority", "structure"], keywordsTr: ["otorite", "yapı"] },
  { id: 5, name: "The Hierophant", nameTr: "Aziz", suit: "major", number: 5, meaning: { upright: "Spiritual wisdom, religious beliefs", reversed: "Personal beliefs, freedom" }, meaningTr: { upright: "Ruhsal bilgelik, dini inançlar", reversed: "Kişisel inançlar, özgürlük" }, keywords: ["tradition", "conformity"], keywordsTr: ["gelenek", "uyum"] },
  { id: 6, name: "The Lovers", nameTr: "Aşıklar", suit: "major", number: 6, meaning: { upright: "Love, harmony, relationships", reversed: "Self-love, disharmony" }, meaningTr: { upright: "Aşk, uyum, ilişkiler", reversed: "Öz sevgi, uyumsuzluk" }, keywords: ["love", "harmony"], keywordsTr: ["aşk", "uyum"] },
  { id: 7, name: "The Chariot", nameTr: "Savaş Arabası", suit: "major", number: 7, meaning: { upright: "Control, willpower, success", reversed: "Self-discipline, opposition" }, meaningTr: { upright: "Kontrol, irade gücü, başarı", reversed: "Öz disiplin, karşıtlık" }, keywords: ["control", "willpower"], keywordsTr: ["kontrol", "irade"] },
  { id: 8, name: "Strength", nameTr: "Güç", suit: "major", number: 8, meaning: { upright: "Strength, courage, persuasion", reversed: "Self doubt, lack of confidence" }, meaningTr: { upright: "Güç, cesaret, ikna", reversed: "Öz şüphe, güven eksikliği" }, keywords: ["strength", "courage"], keywordsTr: ["güç", "cesaret"] },
  { id: 9, name: "The Hermit", nameTr: "Münzevi", suit: "major", number: 9, meaning: { upright: "Soul searching, introspection", reversed: "Isolation, loneliness" }, meaningTr: { upright: "Ruh arayışı, iç gözlem", reversed: "İzolasyon, yalnızlık" }, keywords: ["introspection", "searching"], keywordsTr: ["iç gözlem", "arayış"] },
  { id: 10, name: "Wheel of Fortune", nameTr: "Kader Çarkı", suit: "major", number: 10, meaning: { upright: "Good luck, karma, life cycles", reversed: "Bad luck, lack of control" }, meaningTr: { upright: "İyi şans, karma, yaşam döngüleri", reversed: "Kötü şans, kontrol eksikliği" }, keywords: ["luck", "karma"], keywordsTr: ["şans", "karma"] },
  { id: 11, name: "Justice", nameTr: "Adalet", suit: "major", number: 11, meaning: { upright: "Justice, fairness, truth", reversed: "Unfairness, lack of accountability" }, meaningTr: { upright: "Adalet, hakkaniyet, gerçek", reversed: "Haksızlık, hesap verememe" }, keywords: ["justice", "fairness"], keywordsTr: ["adalet", "hakkaniyet"] },
  { id: 12, name: "The Hanged Man", nameTr: "Asılan Adam", suit: "major", number: 12, meaning: { upright: "Surrender, letting go, sacrifice", reversed: "Delays, resistance, stalling" }, meaningTr: { upright: "Teslim olma, bırakma, fedakarlık", reversed: "Gecikmeler, direnç, oyalama" }, keywords: ["surrender", "sacrifice"], keywordsTr: ["teslim olma", "fedakarlık"] },
  { id: 13, name: "Death", nameTr: "Ölüm", suit: "major", number: 13, meaning: { upright: "Endings, transformation, transition", reversed: "Resistance to change, inner purging" }, meaningTr: { upright: "Sonlar, dönüşüm, geçiş", reversed: "Değişime direnç, içsel arınma" }, keywords: ["transformation", "endings"], keywordsTr: ["dönüşüm", "sonlar"] },
  { id: 14, name: "Temperance", nameTr: "Ölçülülük", suit: "major", number: 14, meaning: { upright: "Balance, moderation, patience", reversed: "Imbalance, excess, self-healing" }, meaningTr: { upright: "Denge, ölçülülük, sabır", reversed: "Dengesizlik, aşırılık, öz şifa" }, keywords: ["balance", "moderation"], keywordsTr: ["denge", "ölçülülük"] },
  { id: 15, name: "The Devil", nameTr: "Şeytan", suit: "major", number: 15, meaning: { upright: "Bondage, addiction, materialism", reversed: "Releasing limiting beliefs, detachment" }, meaningTr: { upright: "Bağımlılık, tutku, materyalizm", reversed: "Sınırlayıcı inançları bırakma, ayrılma" }, keywords: ["bondage", "materialism"], keywordsTr: ["bağımlılık", "materyalizm"] },
  { id: 16, name: "The Tower", nameTr: "Kule", suit: "major", number: 16, meaning: { upright: "Sudden change, upheaval, chaos", reversed: "Personal transformation, fear of change" }, meaningTr: { upright: "Ani değişim, karışıklık, kaos", reversed: "Kişisel dönüşüm, değişim korkusu" }, keywords: ["sudden change", "upheaval"], keywordsTr: ["ani değişim", "karışıklık"] },
  { id: 17, name: "The Star", nameTr: "Yıldız", suit: "major", number: 17, meaning: { upright: "Hope, faith, purpose, renewal", reversed: "Lack of faith, despair, disconnection" }, meaningTr: { upright: "Umut, inanç, amaç, yenilenme", reversed: "İnanç eksikliği, umutsuzluk, kopukluk" }, keywords: ["hope", "faith"], keywordsTr: ["umut", "inanç"] },
  { id: 18, name: "The Moon", nameTr: "Ay", suit: "major", number: 18, meaning: { upright: "Illusion, fear, anxiety, subconscious", reversed: "Release of fear, repressed emotion" }, meaningTr: { upright: "İllüzyon, korku, kaygı, bilinçaltı", reversed: "Korkunun bırakılması, bastırılmış duygu" }, keywords: ["illusion", "fear"], keywordsTr: ["illüzyon", "korku"] },
  { id: 19, name: "The Sun", nameTr: "Güneş", suit: "major", number: 19, meaning: { upright: "Positivity, fun, warmth, success", reversed: "Inner child, feeling down" }, meaningTr: { upright: "Pozitiflik, eğlence, sıcaklık, başarı", reversed: "İç çocuk, moralsizlik" }, keywords: ["positivity", "fun"], keywordsTr: ["pozitiflik", "eğlence"] },
  { id: 20, name: "Judgement", nameTr: "Mahkeme", suit: "major", number: 20, meaning: { upright: "Judgement, rebirth, inner calling", reversed: "Self-doubt, inner critic" }, meaningTr: { upright: "Yargı, yeniden doğuş, içsel çağrı", reversed: "Öz şüphe, içsel eleştirmen" }, keywords: ["judgement", "rebirth"], keywordsTr: ["yargı", "yeniden doğuş"] },
  { id: 21, name: "The World", nameTr: "Dünya", suit: "major", number: 21, meaning: { upright: "Completion, integration, accomplishment", reversed: "Seeking personal closure, short-cut" }, meaningTr: { upright: "Tamamlanma, bütünleşme, başarı", reversed: "Kişisel kapanış arayışı, kısa yol" }, keywords: ["completion", "integration"], keywordsTr: ["tamamlanma", "bütünleşme"] },

  // Minor Arcana - Cups (Kadehler) - 14 kart
  { id: 22, name: "Ace of Cups", nameTr: "Kadehler Ası", suit: "cups", number: 1, meaning: { upright: "New relationships, compassion", reversed: "Self-love, repressed emotions" }, meaningTr: { upright: "Yeni ilişkiler, merhamet", reversed: "Öz sevgi, bastırılmış duygular" }, keywords: ["love", "emotions"], keywordsTr: ["aşk", "duygular"] },
  { id: 23, name: "Two of Cups", nameTr: "Kadehler İkilisi", suit: "cups", number: 2, meaning: { upright: "Partnership, mutual attraction", reversed: "Self-love, break-ups" }, meaningTr: { upright: "Ortaklık, karşılıklı çekim", reversed: "Öz sevgi, ayrılıklar" }, keywords: ["partnership", "love"], keywordsTr: ["ortaklık", "aşk"] },
  { id: 24, name: "Three of Cups", nameTr: "Kadehler Üçlüsü", suit: "cups", number: 3, meaning: { upright: "Celebration, friendship", reversed: "Independence, creative blocks" }, meaningTr: { upright: "Kutlama, dostluk", reversed: "Bağımsızlık, yaratıcı bloklar" }, keywords: ["celebration", "friendship"], keywordsTr: ["kutlama", "dostluk"] },
  { id: 25, name: "Four of Cups", nameTr: "Kadehler Dörtlüsü", suit: "cups", number: 4, meaning: { upright: "Meditation, contemplation", reversed: "Retreat, withdrawal" }, meaningTr: { upright: "Meditasyon, düşünce", reversed: "Geri çekilme, içe kapanma" }, keywords: ["meditation", "contemplation"], keywordsTr: ["meditasyon", "düşünce"] },
  { id: 26, name: "Five of Cups", nameTr: "Kadehler Beşlisi", suit: "cups", number: 5, meaning: { upright: "Regret, disappointment", reversed: "Self-forgiveness, moving on" }, meaningTr: { upright: "Pişmanlık, hayal kırıklığı", reversed: "Kendini bağışlama, ilerleme" }, keywords: ["regret", "disappointment"], keywordsTr: ["pişmanlık", "hayal kırıklığı"] },
  { id: 27, name: "Six of Cups", nameTr: "Kadehler Altılısı", suit: "cups", number: 6, meaning: { upright: "Childhood memories, innocence", reversed: "Living in past, forgiveness" }, meaningTr: { upright: "Çocukluk anıları, masumiyet", reversed: "Geçmişte yaşama, bağışlama" }, keywords: ["nostalgia", "childhood"], keywordsTr: ["nostalji", "çocukluk"] },
  { id: 28, name: "Seven of Cups", nameTr: "Kadehler Yedilisi", suit: "cups", number: 7, meaning: { upright: "Opportunities, choices", reversed: "Personal values, overwhelmed" }, meaningTr: { upright: "Fırsatlar, seçimler", reversed: "Kişisel değerler, bunalma" }, keywords: ["opportunities", "choices"], keywordsTr: ["fırsatlar", "seçimler"] },
  { id: 29, name: "Eight of Cups", nameTr: "Kadehler Sekizlisi", suit: "cups", number: 8, meaning: { upright: "Disappointment, abandonment", reversed: "Trying again, indecision" }, meaningTr: { upright: "Hayal kırıklığı, terk etme", reversed: "Tekrar deneme, kararsızlık" }, keywords: ["disappointment", "abandonment"], keywordsTr: ["hayal kırıklığı", "terk etme"] },
  { id: 30, name: "Nine of Cups", nameTr: "Kadehler Dokuzlusu", suit: "cups", number: 9, meaning: { upright: "Contentment, satisfaction", reversed: "Inner happiness, dissatisfaction" }, meaningTr: { upright: "Memnuniyet, tatmin", reversed: "İç mutluluk, memnuniyetsizlik" }, keywords: ["contentment", "satisfaction"], keywordsTr: ["memnuniyet", "tatmin"] },
  { id: 31, name: "Ten of Cups", nameTr: "Kadehler Onlusu", suit: "cups", number: 10, meaning: { upright: "Divine love, harmony", reversed: "Disconnection, struggling relationships" }, meaningTr: { upright: "İlahi aşk, uyum", reversed: "Kopukluk, zorlu ilişkiler" }, keywords: ["divine love", "harmony"], keywordsTr: ["ilahi aşk", "uyum"] },
  { id: 32, name: "Page of Cups", nameTr: "Kadehler Prensi", suit: "cups", meaning: { upright: "Creative opportunities, intuition", reversed: "New ideas, doubting intuition" }, meaningTr: { upright: "Yaratıcı fırsatlar, sezgi", reversed: "Yeni fikirler, sezgiyi şüphe" }, keywords: ["creativity", "intuition"], keywordsTr: ["yaratıcılık", "sezgi"] },
  { id: 33, name: "Knight of Cups", nameTr: "Kadehler Şövalyesi", suit: "cups", meaning: { upright: "Romance, charm, imagination", reversed: "Unrealistic, jealousy" }, meaningTr: { upright: "Romantizm, cazibe, hayal gücü", reversed: "Gerçekçi olmayan, kıskançlık" }, keywords: ["romance", "charm"], keywordsTr: ["romantizm", "cazibe"] },
  { id: 34, name: "Queen of Cups", nameTr: "Kadehler Kraliçesi", suit: "cups", meaning: { upright: "Compassionate, emotionally stable", reversed: "Inner feelings, self-care" }, meaningTr: { upright: "Merhametli, duygusal kararlı", reversed: "İç duygular, öz bakım" }, keywords: ["compassion", "emotional stability"], keywordsTr: ["merhamet", "duygusal kararlılık"] },
  { id: 35, name: "King of Cups", nameTr: "Kadehler Kralı", suit: "cups", meaning: { upright: "Emotionally balanced, diplomatic", reversed: "Self-compassion, moodiness" }, meaningTr: { upright: "Duygusal dengeli, diplomatik", reversed: "Öz merhamet, huysuzluk" }, keywords: ["emotional balance", "diplomacy"], keywordsTr: ["duygusal denge", "diplomasi"] },

  // Minor Arcana - Wands (Asalar) - 14 kart  
  { id: 36, name: "Ace of Wands", nameTr: "Asalar Ası", suit: "wands", number: 1, meaning: { upright: "Inspiration, new opportunities", reversed: "Lack of energy, boredom" }, meaningTr: { upright: "İlham, yeni fırsatlar", reversed: "Enerji eksikliği, can sıkıntısı" }, keywords: ["inspiration", "power"], keywordsTr: ["ilham", "güç"] },
  { id: 37, name: "Two of Wands", nameTr: "Asalar İkilisi", suit: "wands", number: 2, meaning: { upright: "Future planning, decisions", reversed: "Personal goals, fear of unknown" }, meaningTr: { upright: "Gelecek planlama, kararlar", reversed: "Kişisel hedefler, bilinmezlik korkusu" }, keywords: ["planning", "decisions"], keywordsTr: ["planlama", "kararlar"] },
  { id: 38, name: "Three of Wands", nameTr: "Asalar Üçlüsü", suit: "wands", number: 3, meaning: { upright: "Expansion, foresight", reversed: "Playing small, delays" }, meaningTr: { upright: "Genişleme, öngörü", reversed: "Küçük oynama, gecikmeler" }, keywords: ["expansion", "foresight"], keywordsTr: ["genişleme", "öngörü"] },
  { id: 39, name: "Four of Wands", nameTr: "Asalar Dörtlüsü", suit: "wands", number: 4, meaning: { upright: "Celebration, harmony", reversed: "Personal celebration, conflict" }, meaningTr: { upright: "Kutlama, uyum", reversed: "Kişisel kutlama, çatışma" }, keywords: ["celebration", "harmony"], keywordsTr: ["kutlama", "uyum"] },
  { id: 40, name: "Five of Wands", nameTr: "Asalar Beşlisi", suit: "wands", number: 5, meaning: { upright: "Conflict, competition", reversed: "Inner conflict, avoidance" }, meaningTr: { upright: "Çatışma, rekabet", reversed: "İç çatışma, kaçınma" }, keywords: ["conflict", "competition"], keywordsTr: ["çatışma", "rekabet"] },
  { id: 41, name: "Six of Wands", nameTr: "Asalar Altılısı", suit: "wands", number: 6, meaning: { upright: "Success, recognition", reversed: "Private achievement, fall from grace" }, meaningTr: { upright: "Başarı, tanınma", reversed: "Özel başarı, lütuftan düşme" }, keywords: ["success", "recognition"], keywordsTr: ["başarı", "tanınma"] },
  { id: 42, name: "Seven of Wands", nameTr: "Asalar Yedilisi", suit: "wands", number: 7, meaning: { upright: "Challenge, perseverance", reversed: "Exhaustion, giving up" }, meaningTr: { upright: "Meydan okuma, sebat", reversed: "Tükenmişlik, pes etme" }, keywords: ["challenge", "perseverance"], keywordsTr: ["meydan okuma", "sebat"] },
  { id: 43, name: "Eight of Wands", nameTr: "Asalar Sekizlisi", suit: "wands", number: 8, meaning: { upright: "Speed, progress", reversed: "Delays, frustration" }, meaningTr: { upright: "Hız, ilerleme", reversed: "Gecikmeler, hayal kırıklığı" }, keywords: ["speed", "progress"], keywordsTr: ["hız", "ilerleme"] },
  { id: 44, name: "Nine of Wands", nameTr: "Asalar Dokuzlusu", suit: "wands", number: 9, meaning: { upright: "Resilience, courage", reversed: "Inner resources, struggle" }, meaningTr: { upright: "Dayanıklılık, cesaret", reversed: "İç kaynaklar, mücadele" }, keywords: ["resilience", "courage"], keywordsTr: ["dayanıklılık", "cesaret"] },
  { id: 45, name: "Ten of Wands", nameTr: "Asalar Onlusu", suit: "wands", number: 10, meaning: { upright: "Burden, responsibility", reversed: "Doing it all, delegation" }, meaningTr: { upright: "Yük, sorumluluk", reversed: "Hepsini yapma, yetki devri" }, keywords: ["burden", "responsibility"], keywordsTr: ["yük", "sorumluluk"] },
  { id: 46, name: "Page of Wands", nameTr: "Asalar Prensi", suit: "wands", meaning: { upright: "Inspiration, discovery", reversed: "Lack of direction, procrastination" }, meaningTr: { upright: "İlham, keşif", reversed: "Yön eksikliği, erteleme" }, keywords: ["inspiration", "discovery"], keywordsTr: ["ilham", "keşif"] },
  { id: 47, name: "Knight of Wands", nameTr: "Asalar Şövalyesi", suit: "wands", meaning: { upright: "Energy, passion, adventure", reversed: "Haste, scattered energy" }, meaningTr: { upright: "Enerji, tutku, macera", reversed: "Acele, dağınık enerji" }, keywords: ["energy", "passion"], keywordsTr: ["enerji", "tutku"] },
  { id: 48, name: "Queen of Wands", nameTr: "Asalar Kraliçesi", suit: "wands", meaning: { upright: "Courage, independence", reversed: "Self-respect, introverted" }, meaningTr: { upright: "Cesaret, bağımsızlık", reversed: "Öz saygı, içe dönük" }, keywords: ["courage", "independence"], keywordsTr: ["cesaret", "bağımsızlık"] },
  { id: 49, name: "King of Wands", nameTr: "Asalar Kralı", suit: "wands", meaning: { upright: "Leadership, vision", reversed: "Impulsiveness, ruthless" }, meaningTr: { upright: "Liderlik, vizyon", reversed: "Dürtüsellik, acımasız" }, keywords: ["leadership", "vision"], keywordsTr: ["liderlik", "vizyon"] },

  // Minor Arcana - Swords (Kılıçlar) - 14 kart
  { id: 50, name: "Ace of Swords", nameTr: "Kılıçlar Ası", suit: "swords", number: 1, meaning: { upright: "Breakthrough, clarity", reversed: "Confusion, chaos" }, meaningTr: { upright: "Atılım, berraklık", reversed: "Karışıklık, kaos" }, keywords: ["clarity", "breakthrough"], keywordsTr: ["berraklık", "atılım"] },
  { id: 51, name: "Two of Swords", nameTr: "Kılıçlar İkilisi", suit: "swords", number: 2, meaning: { upright: "Difficult decisions, impasse", reversed: "Indecision, confusion" }, meaningTr: { upright: "Zor kararlar, çıkmaz", reversed: "Kararsızlık, karışıklık" }, keywords: ["decisions", "impasse"], keywordsTr: ["kararlar", "çıkmaz"] },
  { id: 52, name: "Three of Swords", nameTr: "Kılıçlar Üçlüsü", suit: "swords", number: 3, meaning: { upright: "Heartbreak, sorrow", reversed: "Releasing pain, optimism" }, meaningTr: { upright: "Kalp kırıklığı, keder", reversed: "Acıyı serbest bırakma, iyimserlik" }, keywords: ["heartbreak", "sorrow"], keywordsTr: ["kalp kırıklığı", "keder"] },
  { id: 53, name: "Four of Swords", nameTr: "Kılıçlar Dörtlüsü", suit: "swords", number: 4, meaning: { upright: "Rest, meditation", reversed: "Exhaustion, burn-out" }, meaningTr: { upright: "Dinlenme, meditasyon", reversed: "Tükenmişlik, yanma" }, keywords: ["rest", "meditation"], keywordsTr: ["dinlenme", "meditasyon"] },
  { id: 54, name: "Five of Swords", nameTr: "Kılıçlar Beşlisi", suit: "swords", number: 5, meaning: { upright: "Conflict, defeat", reversed: "Reconciliation, past resentment" }, meaningTr: { upright: "Çatışma, yenilgi", reversed: "Uzlaşma, geçmiş kırgınlık" }, keywords: ["conflict", "defeat"], keywordsTr: ["çatışma", "yenilgi"] },
  { id: 55, name: "Six of Swords", nameTr: "Kılıçlar Altılısı", suit: "swords", number: 6, meaning: { upright: "Transition, change", reversed: "Personal transition, resistance" }, meaningTr: { upright: "Geçiş, değişim", reversed: "Kişisel geçiş, direnç" }, keywords: ["transition", "change"], keywordsTr: ["geçiş", "değişim"] },
  { id: 56, name: "Seven of Swords", nameTr: "Kılıçlar Yedilisi", suit: "swords", number: 7, meaning: { upright: "Betrayal, deception", reversed: "Imposter syndrome, secrets" }, meaningTr: { upright: "İhanet, aldatma", reversed: "Sahtekar sendromu, sırlar" }, keywords: ["betrayal", "deception"], keywordsTr: ["ihanet", "aldatma"] },
  { id: 57, name: "Eight of Swords", nameTr: "Kılıçlar Sekizlisi", suit: "swords", number: 8, meaning: { upright: "Restriction, imprisonment", reversed: "Self-limiting beliefs, inner critic" }, meaningTr: { upright: "Kısıtlama, hapis", reversed: "Kendini sınırlayan inançlar, iç eleştirmen" }, keywords: ["restriction", "imprisonment"], keywordsTr: ["kısıtlama", "hapis"] },
  { id: 58, name: "Nine of Swords", nameTr: "Kılıçlar Dokuzlusu", suit: "swords", number: 9, meaning: { upright: "Anxiety, fear", reversed: "Inner turmoil, releasing anxiety" }, meaningTr: { upright: "Kaygı, korku", reversed: "İç karmaşa, kaygıyı serbest bırakma" }, keywords: ["anxiety", "fear"], keywordsTr: ["kaygı", "korku"] },
  { id: 59, name: "Ten of Swords", nameTr: "Kılıçlar Onlusu", suit: "swords", number: 10, meaning: { upright: "Painful endings, betrayal", reversed: "Recovery, resisting end" }, meaningTr: { upright: "Acılı sonlar, ihanet", reversed: "İyileşme, sona direnme" }, keywords: ["endings", "betrayal"], keywordsTr: ["sonlar", "ihanet"] },
  { id: 60, name: "Page of Swords", nameTr: "Kılıçlar Prensi", suit: "swords", meaning: { upright: "New ideas, curiosity", reversed: "Self-expression, no action" }, meaningTr: { upright: "Yeni fikirler, merak", reversed: "Kendini ifade etme, eylem yok" }, keywords: ["ideas", "curiosity"], keywordsTr: ["fikirler", "merak"] },
  { id: 61, name: "Knight of Swords", nameTr: "Kılıçlar Şövalyesi", suit: "swords", meaning: { upright: "Ambitious, action-oriented", reversed: "Restless, impulsive" }, meaningTr: { upright: "Hırslı, eylem odaklı", reversed: "Huzursuz, dürtüsel" }, keywords: ["ambition", "action"], keywordsTr: ["hırs", "eylem"] },
  { id: 62, name: "Queen of Swords", nameTr: "Kılıçlar Kraliçesi", suit: "swords", meaning: { upright: "Independent, clear boundaries", reversed: "Overly-emotional, cold-hearted" }, meaningTr: { upright: "Bağımsız, net sınırlar", reversed: "Aşırı duygusal, soğuk kalpli" }, keywords: ["independence", "boundaries"], keywordsTr: ["bağımsızlık", "sınırlar"] },
  { id: 63, name: "King of Swords", nameTr: "Kılıçlar Kralı", suit: "swords", meaning: { upright: "Mental clarity, authority", reversed: "Quiet power, misuse of power" }, meaningTr: { upright: "Zihinsel berraklık, otorite", reversed: "Sessiz güç, gücün kötüye kullanımı" }, keywords: ["clarity", "authority"], keywordsTr: ["berraklık", "otorite"] },

  // Minor Arcana - Pentacles (Altınlar) - 14 kart
  { id: 64, name: "Ace of Pentacles", nameTr: "Altınlar Ası", suit: "pentacles", number: 1, meaning: { upright: "New opportunity, manifestation", reversed: "Lost opportunity, lack of planning" }, meaningTr: { upright: "Yeni fırsat, tezahür", reversed: "Kaçırılan fırsat, planlama eksikliği" }, keywords: ["opportunity", "manifestation"], keywordsTr: ["fırsat", "tezahür"] },
  { id: 65, name: "Two of Pentacles", nameTr: "Altınlar İkilisi", suit: "pentacles", number: 2, meaning: { upright: "Multiple priorities, adaptability", reversed: "Over-committed, disorganisation" }, meaningTr: { upright: "Çoklu öncelikler, uyum", reversed: "Aşırı taahhüt, düzensizlik" }, keywords: ["priorities", "adaptability"], keywordsTr: ["öncelikler", "uyum"] },
  { id: 66, name: "Three of Pentacles", nameTr: "Altınlar Üçlüsü", suit: "pentacles", number: 3, meaning: { upright: "Collaboration, learning", reversed: "Disharmony, working alone" }, meaningTr: { upright: "İşbirliği, öğrenme", reversed: "Uyumsuzluk, tek başına çalışma" }, keywords: ["collaboration", "learning"], keywordsTr: ["işbirliği", "öğrenme"] },
  { id: 67, name: "Four of Pentacles", nameTr: "Altınlar Dörtlüsü", suit: "pentacles", number: 4, meaning: { upright: "Saving money, security", reversed: "Over-spending, generosity" }, meaningTr: { upright: "Para biriktirme, güvenlik", reversed: "Aşırı harcama, cömertlik" }, keywords: ["saving", "security"], keywordsTr: ["biriktirme", "güvenlik"] },
  { id: 68, name: "Five of Pentacles", nameTr: "Altınlar Beşlisi", suit: "pentacles", number: 5, meaning: { upright: "Financial loss, isolation", reversed: "Recovery from loss, spiritual poverty" }, meaningTr: { upright: "Mali kayıp, izolasyon", reversed: "Kayıptan kurtulma, ruhsal yoksulluk" }, keywords: ["loss", "isolation"], keywordsTr: ["kayıp", "izolasyon"] },
  { id: 69, name: "Six of Pentacles", nameTr: "Altınlar Altılısı", suit: "pentacles", number: 6, meaning: { upright: "Giving, sharing wealth", reversed: "Self-care, unpaid debts" }, meaningTr: { upright: "Verme, zenginlik paylaşımı", reversed: "Kendine bakım, ödenmemiş borçlar" }, keywords: ["giving", "sharing"], keywordsTr: ["verme", "paylaşım"] },
  { id: 70, name: "Seven of Pentacles", nameTr: "Altınlar Yedilisi", suit: "pentacles", number: 7, meaning: { upright: "Perseverance, investment", reversed: "Lack of long-term view, impatience" }, meaningTr: { upright: "Sebat, yatırım", reversed: "Uzun vadeli görüş eksikliği, sabırsızlık" }, keywords: ["perseverance", "investment"], keywordsTr: ["sebat", "yatırım"] },
  { id: 71, name: "Eight of Pentacles", nameTr: "Altınlar Sekizlisi", suit: "pentacles", number: 8, meaning: { upright: "Mastery, skill development", reversed: "Perfectionism, lack of commitment" }, meaningTr: { upright: "Ustalık, beceri geliştirme", reversed: "Mükemmeliyetçilik, bağlılık eksikliği" }, keywords: ["mastery", "skill"], keywordsTr: ["ustalık", "beceri"] },
  { id: 72, name: "Nine of Pentacles", nameTr: "Altınlar Dokuzlusu", suit: "pentacles", number: 9, meaning: { upright: "Abundance, financial independence", reversed: "Self-worth, over-investment" }, meaningTr: { upright: "Bolluk, mali bağımsızlık", reversed: "Öz değer, aşırı yatırım" }, keywords: ["abundance", "independence"], keywordsTr: ["bolluk", "bağımsızlık"] },
  { id: 73, name: "Ten of Pentacles", nameTr: "Altınlar Onlusu", suit: "pentacles", number: 10, meaning: { upright: "Wealth, family, long-term success", reversed: "Financial failure, dark side of wealth" }, meaningTr: { upright: "Zenginlik, aile, uzun vadeli başarı", reversed: "Mali başarısızlık, zenginliğin karanlık tarafı" }, keywords: ["wealth", "family"], keywordsTr: ["zenginlik", "aile"] },
  { id: 74, name: "Page of Pentacles", nameTr: "Altınlar Prensi", suit: "pentacles", meaning: { upright: "Manifestation, financial opportunity", reversed: "Lack of progress, procrastination" }, meaningTr: { upright: "Tezahür, mali fırsat", reversed: "İlerleme eksikliği, erteleme" }, keywords: ["manifestation", "opportunity"], keywordsTr: ["tezahür", "fırsat"] },
  { id: 75, name: "Knight of Pentacles", nameTr: "Altınlar Şövalyesi", suit: "pentacles", meaning: { upright: "Hard work, routine", reversed: "Self-discipline, feeling stuck" }, meaningTr: { upright: "Sıkı çalışma, rutin", reversed: "Öz disiplin, sıkışmış hissetme" }, keywords: ["work", "routine"], keywordsTr: ["çalışma", "rutin"] },
  { id: 76, name: "Queen of Pentacles", nameTr: "Altınlar Kraliçesi", suit: "pentacles", meaning: { upright: "Nurturing, practical", reversed: "Financial independence, work-home conflict" }, meaningTr: { upright: "Besleyici, pratik", reversed: "Mali bağımsızlık, iş-ev çatışması" }, keywords: ["nurturing", "practical"], keywordsTr: ["besleyici", "pratik"] },
  { id: 77, name: "King of Pentacles", nameTr: "Altınlar Kralı", suit: "pentacles", meaning: { upright: "Financial success, business acumen", reversed: "Financial advice, living beyond means" }, meaningTr: { upright: "Mali başarı, iş zekası", reversed: "Mali tavsiye, gücünün üstünde yaşama" }, keywords: ["success", "business"], keywordsTr: ["başarı", "iş"] }
] 